name: build

on:
  push:
    branches: [ "*" ]
  pull_request:

permissions:
  contents: write # required for tagging
  checks: write # required for junit reporting
  actions: write # managing uploaded artifacts

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  gradle_build:
    timeout-minutes: ${{ inputs.timeout-minutes }}
    container:
      image: : "eclipse-temurin:25-jdk"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Build
        run: ./gradlew build
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/build/**/TEST-*.xml'
